apiVersion: v1
kind: Service
metadata:
  name: {{ include "curvine.masterServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "curvine.masterLabels" . | nindent 4 }}
  {{- with .Values.service.master.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  publishNotReadyAddresses: true
  ports:
    - name: rpc
      port: {{ .Values.master.rpcPort }}
      targetPort: {{ .Values.master.rpcPort }}
      protocol: TCP
    - name: journal
      port: {{ .Values.master.journalPort }}
      targetPort: {{ .Values.master.journalPort }}
      protocol: TCP
    - name: web
      port: {{ .Values.master.webPort }}
      targetPort: {{ .Values.master.webPort }}
      protocol: TCP
    - name: web1
      port: {{ .Values.master.web1Port }}
      targetPort: {{ .Values.master.web1Port }}
      protocol: TCP
  selector:
    {{- include "curvine.masterSelectorLabels" . | nindent 4 }}
